# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ricky < Formula
  desc "Open a random Wikipedia article in your browser"
  homepage "https://github.com/dnsbty/ricky"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dnsbty/ricky/releases/download/v0.1.1/ricky_0.1.1_Darwin_arm64.tar.gz"
      sha256 "092629ae1dc3db816d856b236fe6516c0b340c647d918072661735496cbea6da"

      def install
        bin.install "ricky"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dnsbty/ricky/releases/download/v0.1.1/ricky_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "7ebddf00eda5785feea27a342941efe5b443f7c4296eb143507d5b7e7ab836e4"

      def install
        bin.install "ricky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dnsbty/ricky/releases/download/v0.1.1/ricky_0.1.1_Linux_arm64.tar.gz"
      sha256 "9079f292e2cfdda11da8fee8f2e2978e2e371c9b360b50a61ec3ea6875a221cf"

      def install
        bin.install "ricky"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dnsbty/ricky/releases/download/v0.1.1/ricky_0.1.1_Linux_x86_64.tar.gz"
      sha256 "99ef191832fcbb8034f13a2b7354553b8b35867881bfb333aac5099549076f78"

      def install
        bin.install "ricky"
      end
    end
  end
end
